### PR TITLE
Added Symfony 3 support

### PR DESCRIPTION
**Pull request by chirimoya**
https://github.com/phpcr/phpcr-migrations/pull/5

### CODE REVIEW

**Comment by dantleech** [comment]
Hmm travis tests failing with memory issues, will have to have a look later.

**Comment by chirimoya** [comment]
Maybe the minimum-stability dev causes this error. Looks like the object graph get too big.

**Comment by chirimoya** [comment]
https://github.com/sulu/sulu/issues/2106

**Comment by dantleech** [comment]
Lets switch it to `stable` and see what happens, don't think there is any good reason why it should be `dev`

**Comment by chirimoya** [comment]
@dantleech ... now only the symfony 2.3 tests are failing, but it looks like it was already broken ... https://travis-ci.org/dantleech/phpcr-migrations-bundle/builds/127595329

**Comment by dantleech** [comment]
Yeah, would like to drop that, maybe I will tag a major release.

**Comment by dantleech** [comment]
btw, how is this bundle working out for you guys now? stable? might as well release 1.0 ?

**Comment by chirimoya** [comment]
yes, we use it for our release upgrade migrations. works fine so fare. but maybe @danrot or @wachterjohannes do have more on this topic.

**Comment by wachterjohannes** [comment]
@chirimoya @dantleech it works quite fine for sulu - in my opinion its "improvable" in the future but could be released now

**Comment by danrot** [comment]
For me it's working fine. As I already mentioned in a tweet the interface is pretty straight forward, and I wouldn't know about any huge improvement which could be done right now.

**Pull request merged**
